setup.py
tox.ini

Yay, first thing I tried worked to perfection!
Fixes #12

don't register plugin when running flake8 checks

---

flake8_trio.py
tests/test_flake8_trio.py
tests/trio100_py39.py
tests/trio101.py
tests/trio102.py
tox.ini

Pulled out a bunch of small changes from #17 (and applied them a bit more consistently) that aren't relevant to that error code.
`git checkout --patch` is a wunderkind :heart:

various small fixes and improved test output

---

flake8_trio.py
tests/test_flake8_trio.py
tests/trio107.py

Branched off of multi-problem PR, further improving error printing and catching some type errors here and there, although this is once again hitting overkill territory especially with not that many more tests left to create.

More detailed error printing on failed tests

---

CHANGELOG.md
flake8_trio.py
tests/test_flake8_trio.py
tests/trio108.py

On top of #27 so the diff is reasonable large.
Needed to improve the printing a bit to get a handle on the errors flying around, but the extra logic wasn't too bad.
Also solved the case of lazily evaluated boolops

7 async iterable checkpoints

---

tests/test_flake8_trio.py

Fix the remainder of #29
It fails for the obvious reason of TRIO108 being fixed in #31 and this would catch that.

generate sync code from tests

---

CHANGELOG.md
README.md
flake8_trio.py
tests/trio103.py

fixes #35 
I'm not sure this really affects any code out there, but 103 should cover all theoretical cases now other than weird nested try's, afaik.

103 no longer ignore raises in else, unless there's a break

---

CHANGELOG.md
flake8_trio.py
tests/trio103.py
tests/trio107.py
tests/trio108.py

fixes #41 
Also handles dicts, basic `range()` calls, and some fun edge cases with infinite loops and stuff.
Have not incremented version due to multiple open PR's

handle loops that are guaranteed to loop in 103 and 107/108

---

CHANGELOG.md
flake8_trio.py
tests/trio108.py

ignore 107/108 in asynccontextmanager, asyncWith always checkpoint on both entry and exit

---

CHANGELOG.md
flake8_trio.py
tests/trio107.py
tests/trio108.py

Logic can maybe be simplified depending on #48

fix false alarm on trio107 with checkpoint in try and empty finally

---

CHANGELOG.md
flake8_trio.py
tests/trio107.py
tests/trio108.py

So satisfying when all the tools available makes a fix close to trivial to implement.
Replaced all instances of `while ...` in the test files since `bool(...)` is True.
Fixes #47

Fix trio107&108 false alarm on infinite loops

---

flake8_trio.py
tests/test_flake8_trio.py
tests/trio112.py
tests/trio113.py

Fixes #63 
So beautiful that it ended up just being a one-line diff in the actual code :sparkles:

Extend 113 to check for the method name anywhere in the first parameter

---

CHANGELOG.md
README.md
flake8_trio.py
tests/test_flake8_trio.py
tests/trio900.py

Fixes #96 
Just over 30 minutes! Not a record, but :speedboat: 
Couldn't resist solving disabled-by-default with a decorator know that I'd figured out how to do that :innocent:

Add TRIO900 - async generator without known safe decorator

---

CHANGELOG.md
README.md
flake8_trio.py
tests/trio240.py

First bullet point of path manipulation in #58
Suspect this may be overly broad or trigger false alarms, but we'll see.

add trio240, usage of os.path in async function

---

CHANGELOG.md
README.md
flake8_trio/__init__.py
flake8_trio/base.py
flake8_trio/visitors/visitors.py
setup.py
tests/eval_files/trio114.py
tests/eval_files/trio116.py
tests/test_all_visitors_imported.py
tests/test_decorator.py
tests/test_flake8_trio.py

Addressing comments in #103 
Only question mark is whether to also remove "and Contributors" in `setup.py`.
Also added an extra newline in a test, cuz it was bothering me with the way I run tests.

Small followup fixes and changes to 114 & 116 after the file split

---

CONTRIBUTING.md

Updated CONTRIBUTING.md to suggest pre-commit instead of outdated tox -e check

---

flake8_trio/visitors/visitor2xx.py
tests/eval_files/trio232.py

Any one of these unhandled cases probably isn't too bad to handle - but to handle all of them would end up making this a pretty complex check. See #110 
But if you think any in particular is a common pattern, I can implement that.

trio232 now also handles annotated assignments, and added lots of tests

---

CHANGELOG.md
README.md
flake8_trio/__init__.py
flake8_trio/visitors/__init__.py
flake8_trio/visitors/helpers.py
flake8_trio/visitors/visitor103_104.py
flake8_trio/visitors/visitor91x.py
tests/eval_files/trio910.py
tests/eval_files/trio911.py
tests/test_changelog_and_version.py
tests/test_decorator.py
tests/test_flake8_trio.py

Fixes #117 
mmmm, so easy to implement :relaxed:

Rename 107/108 to 910/911, and make them optional

---

flake8_trio/__init__.py
tests/__init__.py
tests/eval_files/trio212.py
tests/eval_files/trio232.py
tests/test_changelog_and_version.py
tox.ini

only introduced one branch not covered by tests during the three weeks with disabled coverage at least ^^
Accidentally removed in #99

reenable coverage, fix missing coverage

---

flake8_trio/runner.py
flake8_trio/visitors/__init__.py
flake8_trio/visitors/flake8triovisitor.py
flake8_trio/visitors/helpers.py
flake8_trio/visitors/visitor105.py
flake8_trio/visitors/visitor2xx.py
flake8_trio/visitors/visitor_utility.py
flake8_trio/visitors/visitors.py

Some housekeeping in preparation for #121 and future functionality that wants to use type tracking.

Add shared state, move 105 to own visitor file, move utility functionality out to new file visitor_utility.py

---

CHANGELOG.md
flake8_trio/visitors/visitors.py
tests/eval_files/trio900.py

fix TRIO900 false alarm in nested functions

---

README.md

Capitalize errors

---

flake8_trio/visitors/helpers.py
tests/eval_files/trio103.py
tests/eval_files/trio911.py
tests/test_exception_on_invalid_code.py

fixes #147 and extended the fix to ast (TRIO103/104)

raise RuntimeError on invalid literal values to range expression

---

CHANGELOG.md
flake8_trio/visitors/visitor91x.py
tests/eval_files/trio910.py
tests/eval_files/trio911.py

fixes #144 
Fairly straightforward implementation, other than the gnarly logic.

add comprehension support to 91x

---

.github/workflows/ci.yml

test_version_and_changelog -> test_changelog_and_version

fix ci typo in release

---

.github/workflows/ci.yml

should hopefully be the last issue, missed this when copying from shed's ci.yml
fixes #168 
The actual diff you should look at is #170 - which I accidentally merged (rebased even) onto main

Install gitpython

---

tests/test_flake8_trio.py

fixes #172 (I hope, this was modified in my local files but not committed+pushed, so I hope past self was smart)

disable deadline for unreliable timing test

---

setup.py
tests/test_config_and_args.py

~~probably smallest PR to date ^^~~ alas, past me had written tests

rename console script flake8_trio -> flake8-trio

---

CHANGELOG.md
README.md
flake8_async/__init__.py
flake8_async/visitors/visitor2xx.py
tests/eval_files/async250.py
tests/eval_files/async250_multi_library.py
tests/test_changelog_and_version.py

add ASYNC250: blocking sync call input() in async function.

---

tests/test_config_and_args.py

more stuff I happened to find lying around in a branch. This is just some small improvements to test_config_and_args around handling flake8>=6's new errors

various fixes to config tests

---

docs/requirements.txt

See https://github.com/felix-hilden/sphinx-codeautolink/issues/153

unpin codeautolink

---

tests/eval_files/async900_trio.py

it appears I forgot to add this file

Async900 as safe channel
