python-trio/flake8-async

README.md
flake8_trio.py
tests/test_flake8_trio.py
tests/trio101.py
tox.ini

Not entirely sure dumping a bunch of yields into a set is the best way to avoid false positives, but other than doing the reverse (saving `contextmanagers`/`functiondefs`, or their linenos) I couldn't figure out a neater way of doing it.
Didn't bother trying to juggle out trio100 changes, so you might want to merge the first pull request before looking at this diff.

Trio101: Never yield inside a nursery or cancel scope

---

CHANGELOG.md
README.md
flake8_trio.py
tests/test_flake8_trio.py
tests/trio101.py
tests/trio102.py
tests/trio102_py39.py

A first draft of trio102. check_for_102 is kind of a mess, with having to inspect a lot of places to find cancel scopes, if they have a timeout specified, and if shielding is set. (It appears there was a shield parameter in the past that now is gone?). It might be a bit defensive and checking the parameter of the trio call is probably silly since they require one.
It also fails on fuzzing site code, since they do have `await`'s in `finally`'s and this doesn't care if they're related much to trio at all. Maybe add a global check that the file has to import or mention trio?
`trio102.py` has a fun case on line 39 (that will fail on python3.8 atm) that idk if it's worth caring about?
And it adds duplicates and is generally kinda ugly, but thought I'd push a first draft to see if I've …

Trio102: await inside finally needs shielding and timeout

---

CONTRIBUTING.md
tox.ini

To save the pain of pushing code only to have it fail on github CI version tests I looked up how to set up tests against different environments directly in tox, and this works well. Added a default envlist so `tox` doesn't take forever.
With this you'll have to slightly change the CI calls (e.g. `-e py38-test` in the python3.8 test environment).
I noticed you said 3.7 -- 3.11 back in your e-mail though. Running the code against 3.11 takes forever and a library uses a deprecated feature that fails the test, so that seems not worth it. But wanted to double-check whether you want to test against 3.7 or not.

generate test environments for 3.8, 3.9 and 3.10

---

README.md
flake8_trio.py
tests/test_changelog_and_version.py
tests/test_flake8_trio.py
tests/test_trio_tests.py
tests/trio100.py
tests/trio100_py39.py
tests/trio102.py
tests/trio105.py
tests/trio106.py

Fixes #13 
Also found what I think is a bug in TRIO100, and added TRIO106 to `README.md`

Meta-tests

---

CHANGELOG.md
README.md
flake8_trio.py
tests/test_flake8_trio.py
tests/trio102.py
tests/trio103_104.py
tests/trio107_108.py

Also add info to error messages on 102&103, rename variables and minor refactor of Visitor102 to match later visitors.

Extend 102 to excepts, 104 also catch yield

---

CHANGELOG.md
README.md
flake8_trio.py
tests/trio300.py

Easy check, only question mark is if `*timeout` or `**timeout` is worthy of raising a problem.
Have not incremented version number, and 300 is a temporary error code until we've sorted out what to do with #17

Add trio[300], async functions should not have a timeout parameter

---

CONTRIBUTING.md
tests/test_flake8_trio.py

Forked off from #17 for a smaller diff

improved printing, added INCLUDE

---

CHANGELOG.md
flake8_trio.py
tests/trio108.py

Fixes (part of) #29
Should also speed up checker on sync code
Also double checked if any of the other codes that should only raise on async might run on sync, and it should not be possible.

fix 108 yields raising error in sync functions

---

CHANGELOG.md
flake8_trio.py
tests/trio109.py

Fix #24 
Sort of feels like there should be a flag/config option for this though

TRIO109: skip decorated functions

---

flake8_trio.py
tests/test_changelog_and_version.py
tests/test_flake8_trio.py
tests/trio103.py

Looks like there's bugs in both mypy and pylint with regards to the `__eq__` in Statement in flake8_trio.py (nobody mentions NamedTuple in https://github.com/python/mypy/issues/6910 - but I think it's the same?), and while the pylint issue https://github.com/PyCQA/pylint/issues/225 is closed it's cropping up in `checkpoint_continue/break` as well.
But with 11 disabled flags flake8_trio and tests/test* now pass without any errors - though if pylint was added to tox a few of those would probably be `#pylint: disable=XXX` instead.
I elected to explicitly set encoding in all opens as well, according to https://peps.python.org/pep-0597/
I also wiped a redundant test after running `pylint --disable=all --enable=similarities tests/trio*` - but that also gives a bunch of false positives. Though I …

pylint pass

---

CHANGELOG.md
README.md
flake8_trio.py
tests/trio112.py

Final remaining issue without a PR :muscle: 
Code is fugly, will make a pass tomorrow, but I think the check is done.

TRIO112: replace one-line nursery with regular function call

---

tests/test_flake8_trio.py

Wrote this up while finagling with 107/108 and wanted to see how much of those issues were caused by 103. Ultimately didn't keep the added comments in the 107/108 files to minimize diff, but might as well push this for future use.
So can now do e.g.
```python
try:
...
except: # TRIO103: 0, 'bare except'
...
finally:
yield # TRIO108: [...]
```
Could then also add possibility of test file not matching an error code, in case all errors in it have the code specified.

allow other specified errors in test file

---

.github/workflows/ci.yml
tests/test_flake8_trio.py
tox.ini

When writing #49 I got paranoid about all the possible permutations and kept adding more and more tests to the file - so bashed out this one instead.
Since it creates a couple thousand tests it might be worth putting this behind another pytest mark [and not run by default?], and/or add back `xdist`.
The test added fails since it depends on the functionality of #49

added parametrized test of all possible permutations of try with 107

---

flake8_trio.py
tests/trio102.py

Fixes #54 
Man I'm happy with the borderline overkill testing infrastructure, *so* lovely to just change the comment and have the auto-generated test updated :blush: 
Also removed `context_manager_names` directly specifying them for trio101 since it's now the only one that cares about them.

trio102 now ignores contextmanager

---

CHANGELOG.md
README.md
flake8_trio.py
tests/trio105.py

Took me a second to remember what the rest of the code in the 105 checker did, so added a corresponding comment at line 812 otherwise unrelated to this PR.
fixes #56

expand 105 to also check for nursery.start

---

CHANGELOG.md
README.md
flake8_trio.py
tests/test_decorator.py
tests/test_flake8_trio.py
tests/trio113.py

Fixes #57 
Quick and dirty:
* the message probably needs bettering.
* require that the object `start_soon` is called on is called "nursery"?
* require that it's also inside a `with`?
* could probs extend tests, but I think I covered most cases.
* maybe doesn't need it's own class, but since speed hasn't been an issue /shrug
* add config option

add TRIO113, nursery.start_soon() in async context manager

---

tests/test_flake8_trio.py

fixes #77 
you might also want to go through that list and check that those are errors that should all be raised on fully sync code, though if they'd been raising false alarms you'd probably noticed by now.

change sync_errors so user has to add errors that should be ignored

---

flake8_trio.py
tests/trio102.py

The PR is split into two commits, the first does the refactoring, the second splits up VisitorMiscChecks (turns out some comments were wrong in what visitors in it were necessary for which checks...) so most of those checks should be easier to read. So I'd recommend reading the diffs for those separately.
Was somewhat tricky to get this working with some of the very particular checks - and so it doesn't fully only iterate through the tree once. If a `visit_` function calls `self.visit()` (either directly or through `self.generic_visit()`/`self.visit_nodes()`) it will set a flag `self.novisit` which tells the external runner to exclude that class when visiting subnodes so they're not visited twice.
To not have to do that too often I added `Flake8TrioVisitor.save_state(node)` which serves …

Reformat to use external runner

---

flake8_trio.py
tests/test_changelog_and_version.py
tests/test_decorator.py
tests/test_flake8_trio.py
tests/trio113.py
tests/trio114.py

also changes test_113 and 114_options to use ARGS (since they broke from this it was a good opportunity to rewrite them).
> As a follow-up, it'd be nice for each visitor class to have a docstring briefly explaining what they do - just copying the relevant line from the readme would be plenty.
Yeah this has been sorely needed for a while, I started copy-pasting but started feeling very silly about it so the visitor classes now define their error codes themselves.
Would be fun to move the documentation from the readme into them and auto-generate docs (+ the same for command line args) as well, but that's probs overkill - although having to keep documentation correct in several different files & places is always a pain.

move error codes into visitor classes

---

README.md
flake8_trio.py
tests/test_flake8_trio.py

Very dirty workaround for #84 in case you want it fixed quickly.
Spaces in the "suggested replacement", or around `->`, are still broken.
Also noticed a typo in the readme

Config error

---

flake8_trio.py
tests/test_decorator.py
tests/test_flake8_trio.py

Also some false alarms that I ended up wrapping in "\`\`"

eradicate commented out code

---

CHANGELOG.md
flake8_trio.py
tests/trio200.py

Fixes #85
Maybe nicer to rename the variable as well, but didn't immediately come up with a great name and class is small enough it won't really matter.

don't raise TRIO200 if the call is immediately awaited.

---

flake8_trio.py
tests/test_decorator.py
tests/test_flake8_trio.py

*Huge* PR :grin: 
Not sure why that colon was added in the first place, but the plugin now finally works with flake8-noqa's `NQA102` and `NQA103`

fix flake8-noqa compatibility

---

.github/workflows/ci.yml
.pre-commit-config.yaml
flake8_trio.py
tests/conftest.py
tests/test_decorator.py
tests/test_flake8_trio.py
tox.ini

It bit me a bunch of times that I didn't run tox before pushing minor changes, and `tox -e check` takes 13s on my system, so I've gradually recreated all the functionality from it in pre-commit + some other checks. So at this point it might be worth removing `tox -e check` entirely and transitioning the CI to use pre-commit as well. If you approve of the idea I'll implement the necessary gh CI changes as well & clean up `tox.ini`.
~~(though it currently won't pass until #87 is merged)~~
TODO:

add pre-commit config

---

CHANGELOG.md
CONTRIBUTING.md
README.md
flake8_trio.py
tests/test_changelog_and_version.py
tests/test_flake8_trio.py
tests/trio210.py
tests/trio211.py
tests/trio22x.py

Checking off the first couple sync calls in #58 
`Flake8TrioVisitor.__subclasses__` didn't do it anymore once I started using multilevel inheritance, so solved it by creating a decorator for error classes that registers them. (type hinting the decorator function was fun :sweat_smile:)
Wasn't sure if the http calls and process invocation bullet points wanted different error messages for each, and the messages themselves are kinda rough, but went with this for a first pass.
TODO:
Don't bother merging both this and #91, merge one and I'll fix the conflicts in the other.

21X and 22X, blocking sync calls in async function

---

CHANGELOG.md
README.md
flake8_trio.py
tests/trio22x.py
tests/trio23x.py

First bullet point of #58 
> Use `trio.open_file()` instead of `open()`, `io.open`, `io.open_code`, or `os.fdopen` in async functions
Although I guessed that `os.fdopen` should be wrapped in `trio.wrap_file` as per the intro
I have *no* idea how to stop shed/pyupgrade from reformatting `io.open` into `open`, tried both `#fmt: off` and `#noqa`.

Add TRIO23x, sync IO call in async function

---

.github/workflows/ci.yml
.pre-commit-config.yaml
tox.ini

Fixes #97 
Re-renamed back typing to check, and GH CI now runs all of pre-commit and not just pyright.

run all of pre-commit directly from the gh CI action

---

CHANGELOG.md
README.md
flake8_trio/__init__.py
flake8_trio/visitors/visitors.py
tests/eval_files/trio900.py

Split this out cause I wasn't sure if it was going to be a bigger PR - but ended up being quite manageable.

TRIO900 now only checks for asynccontextmanager, ignoring flags

---

CHANGELOG.md
README.md
flake8_trio/visitors/visitor2xx.py
tests/eval_files/trio232.py

A first draft at tracking types for file/path/httpx/etc and warning on sync calls. Except this one just does it for `open()` and the varios `io.*` types it can return as a start.
This and others that build on top of it should finish off #58 
Branched from on top of #103 - but you can just view the latest commit to see the contents of this one.
* The logic for tracking variables and their type will be moved to a superclass that different error_classes can inherit from (or possibly just implemented in `Flake8TrioVisitor`.
* Child classes will probably be able to register calls and their return type so the superclass can use that. (so something like `super().register('open', 'io.TextIOWrapper')` in the `__init__`
* code can then maybe be reused for the error classes tracking nurseries
* I …

Add TRIO232: blocking sync call on file objects

---

CHANGELOG.md
README.md
flake8_trio/visitors/visitor103_104.py
tests/eval_files/trio103.py
tests/eval_files/trio103_no_104.py
tests/eval_files/trio104.py

Fixes #106 
Also fixes several other cases not mentioned in the issue, and does the same for TRIO104.
Took me a minute to understand the existing 103/104 implementation and where to inject the logic for this, but ultimately a pretty simple addition.
It broke, like, *all* of the 103/104 tests though since they didn't bother having separate `try`s for the excepts, so went ham on adding those. But I didn't bother fixing `trio103_no_104.py` and cut that down to the minimal tests needed to check what that one actually checks. (that 103 is enabled, and not 104, when only one of them is selected with the regex).
But at the end of `trio103.py` and `trio104.py` are the new test cases added

Fix TRIO103 false alarm on excepts after a previous except has caught Cancelled

---

CHANGELOG.md
README.md
flake8_trio/visitors/visitors.py
tests/eval_files/trio117.py
tests/test_flake8_trio.py

Fixes #105 
I made some assumptions when writing the README message, and the error message could maybe be more informative.
Otherwise a very simple and straightforward check. I could restrict it to raise/catch/methods if this is too liberal, but simplest was to just trigger on any name/attribute and not care about context.

add TRIO117, error on any reference to multierror

---

.pre-commit-config.yaml
pyproject.toml
tests/test_changelog_and_version.py

Makes it so #113 won't happen again

add codespell to pre-commit, add exception for spawnve, rename aline variable

---

CHANGELOG.md
README.md
flake8_trio/visitors/flake8triovisitor.py
flake8_trio/visitors/visitor2xx.py
tests/eval_files/trio212.py
tests/eval_files/trio232.py

Ticks another box in #58 
All the code ... just worked .. on the first try?? I got so paranoid about the testing infrastructure being broken, but nope - turns out I was just writing correct code over and over.
Not the prettiest class structure since the type-tracking class can't be reused for classes that don't want to inherit from Visitor200, but I'll fix that if/when I want to do that. Or does nurseries want this functionality? Or anything else?
The diff looks relatively large because a big chunk of code is moved without being modified, but this should otherwise be pretty straightforward to review.

add TRIO212: sync call on httpx.Client, move type-tracking logic

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
flake8_trio/visitors/visitor2xx.py
tests/eval_files/trio103.py
tests/eval_files/trio104.py
tests/eval_files/trio107.py
tests/eval_files/trio108.py
tests/eval_files/trio112.py
tests/eval_files/trio117.py
tests/eval_files/trio200.py
tests/eval_files/trio22x.py
tests/eval_files/trio232.py

Since https://docs.python.org/3/library/os.html#os.posix_spawn recommends using `subprocess.run` instead I assumed it should use the same error message as it.
Feels kinda hard to give a good drop-in replacement for `os.wait*` since it may be used for so much, but made a guess - feel free to suggest something else.
Closes #58 at last! And also makes flake8-async fully redundant

Add TRIO222, extend TRIO221, flake8-async redundant

---

flake8_trio/visitors/flake8triovisitor.py
flake8_trio/visitors/visitor102.py
flake8_trio/visitors/visitor103_104.py
flake8_trio/visitors/visitor2xx.py
flake8_trio/visitors/visitor91x.py
flake8_trio/visitors/visitors.py
tests/eval_files/trio103.py
tests/eval_files/trio103_no_104.py
tests/eval_files/trio104.py
tests/test_changelog_and_version.py
tests/test_flake8_trio.py
tests/test_formatting.py

Add test that all error messages end with period (and fix those that didn't). Add better implementation of alt messages for error codes. Also checks that errors in eval files with explicit codes are enabled.
Didn't wanna get started on something meaty but felt like doing something, so just some small maintenance/cleanup.

Add test that all error messages end with period, minor fixes

---

CHANGELOG.md
README.md
flake8_trio/visitors/__init__.py
flake8_trio/visitors/flake8triovisitor.py
flake8_trio/visitors/visitor118.py
tests/eval_files/trio118.py
tests/test_flake8_trio.py

Fixes
> We probably also want to lint for "no assigning that result because it breaks our linter, as well as multi-backend programs".
from #122

add TRIO118 - assigning [the value of] anyio.get_cancelled_exc_class to a variable

---

CHANGELOG.md
flake8_trio/visitors/helpers.py
tests/eval_files/trio210.py

Fixes #129 
Introduced in 73c9fc50 when adding support for anyio.

Fix get_matching_call when passed a single string as base.

---

flake8_trio/visitors/flake8triovisitor.py
flake8_trio/visitors/helpers.py
flake8_trio/visitors/visitor100.py
flake8_trio/visitors/visitor101.py
flake8_trio/visitors/visitor91x.py
tests/eval_files/trio100.py
tests/eval_files/trio103.py
tests/eval_files/trio910.py
tests/eval_files/trio911.py
tests/test_flake8_trio.py

This one is *chonky*
I might go over it tomorrow and add review comments to help reviewing it. Although there's not really much to do other than grind through it - and running it on existing code, I wouldn't be shocked if there's crashes or bugs that didn't exist before, so maybe do that before releasing.
I generally optimized for minimizing the diff, rather than writing the best / most logical code - might leave that for a second commit, or do it when implementing autofix. Esp any `isinstance`s should generally not be there when working against libcst.
I rewrote the loop checker to not require two passes, by injecting a fake statement and doing some fancy logic. Quite happy I came up with this solution, much better than the previous super messy one.
Removing redundant checkpoints might …

reimplement 91X in libcst

---

.pre-commit-config.yaml
flake8_trio/__init__.py
flake8_trio/__main__.py
flake8_trio/base.py
pyproject.toml
setup.py
tests/test_config_and_args.py
tests/test_flake8_trio.py

First steps towards having it run as a standalone program, which is required for autofixing.
* takes basic structure from shed, copying `_get_git_repo_root`.
* Add some magic to get argparsing to work both as standalone and as a plugin
* add `flake8_trio/__main__` to run as a module, and a `console_scripts` entry point
* moved out config testing from `test_flake8_trio`, and added a couple tests to test the above
* crossing my fingers that git tests will magically work in the CI environment as well
Also:
* Remove `flake8-bandit` - running `git` directly is .. kinda sus https://flake8.codes/S607/ ; but if `shed` does it I'm not gonna bother, and I'm very much just disabling ~all errors bandit throws, so it's not really contributing anything.
* `reportUnusedCallResult` is frustrating, …

Now able to run as a standalone module or shell program, with limited functionality

---

.pre-commit-config.yaml
tox.ini

I took the liberty of quickly writing a PR for https://github.com/snok/flake8-type-checking/issues/152 - so those `per-file-ignores` can now be removed ^^

update pre-commit revs, flake8-typecheck now ignores stub files

---

.github/workflows/ci.yml
.pre-commit-config.yaml
flake8_trio/visitors/__init__.py
pyproject.toml
tests/test_all_visitors_imported.py
tox.ini

Split out shed for more granular control of the underlying tools, also added auto-formatting for yaml&toml and other minor config changes.

split shed, format&sort toml+yaml

---

flake8_trio/__init__.py
flake8_trio/runner.py
flake8_trio/visitors/helpers.py
flake8_trio/visitors/visitor100.py
flake8_trio/visitors/visitors.py
tests/autofix_files/trio100.py
tests/autofix_files/trio100_simple_autofix.py
tests/conftest.py
tests/eval_files/trio100_simple_autofix.py
tests/test_config_and_args.py
tests/test_flake8_trio.py
tox.ini

Before jumping on autofixing TRIO91X I decided to start with the simpler TRIO100.
Turns out I'd forgotten how messy it is to manipulate code and preserve whitespace, comments, lines, etc etc etc :upside_down_face: 
~~But I remember solving it in shed, so I can probably crib that from there and write some helper function.
Also remaining is actually changing the file on disk, and adding a flag.~~
~~shed/Black/isort is also back to being incredibly annoying, I'll have to figure out a better way of writing autofix files so they don't get fucked with as much as is done currently.~~

implement autofix for TRIO100

---

.pre-commit-config.yaml
flake8_trio/__init__.py
flake8_trio/visitors/helpers.py
pyproject.toml
tests/eval_files/trio103.py
tests/eval_files/trio104.py
tests/eval_files/trio105.py
tests/eval_files/trio910.py
tests/eval_files/trio911.py
tests/test_changelog_and_version.py
tests/test_flake8_trio.py
typings/flake8/options/manager.pyi

Didn't see an option to warn on unreachable code in pyright, and I tried running Vulture for that but that started requiring me to disable 90%+ of it since it doesn't detect that visitor/leave functions are run, and a lot of other weirdness.
So I settled for running .. another type checker :partying_face: But disabled a couple error codes for now.
It did give some decent warnings on eval files though:
* 103: changing if statements' test from `True` to `...` makes it clearer that the test isn't evaluated
* 104: infinite loops at module level turned off type checking (see #155 )
* 105: noreturn calls have to be split out to get type checking
It does feel silly to run double type checkers, but I'm progressively realizing that linting the h*ck out of the eval files is actually useful - …

add mypy to get warnings on unreachable code, fix/ignore various small typing errors

---

CONTRIBUTING.md
flake8_trio/runner.py
flake8_trio/visitors/__init__.py
flake8_trio/visitors/flake8triovisitor.py
flake8_trio/visitors/helpers.py
flake8_trio/visitors/visitor91x.py
flake8_trio/visitors/visitor_utility.py
tests/autofix_files/trio100.py.diff
tests/autofix_files/trio100_simple_autofix.py.diff
tests/autofix_files/trio910.py
tests/autofix_files/trio910.py.diff
tests/autofix_files/trio911.py
tests/autofix_files/trio911.py.diff
tests/autofix_files/trio91x_autofix.py
tests/autofix_files/trio91x_autofix.py.diff
tests/eval_files/trio91x_autofix.py
tests/test_flake8_trio.py

does *still* not finish #70 :sweat_smile: It "merely" inserts checkpoints wherever needed. 
TODO:
And added a couple more tasks to #124 before this is reasonably usable by an end user. That includes checks for whether autofix toggling actually is toggled, which I kinda know isn't done properly by this anyway (but atm it mostly doesn't matter cause the new file doesn't get written without the autofix flag). But I'll leave those for another PR.

implement autofix for 91x

---

.pre-commit-config.yaml
flake8_trio/visitors/visitor103_104.py
flake8_trio/visitors/visitor2xx.py
flake8_trio/visitors/visitors.py
tests/test_flake8_trio.py

They've improved multi-line string handling, which I otherwise find quite irritating with the loads of long strings everywhere (e.g. currently writing help texts for command line args).

Run black with --preview

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml
flake8_trio/__init__.py
flake8_trio/__main__.py
setup.py
tests/test_config_and_args.py

Didn't come up with any good ways of writing an automated test for pre-commit, but tested it locally and against my fork - and therefore finding the catastrophically bad errors in init & setup :sweat_smile: 
I was a bit surprised missing libcst wasn't picked up by tox, but that's because the testenv depends on hypothesmith - which requires libcst.
We surely want to start tagging releases though, I looked at shed's CI workflow if there were anything there that automatically created tags but didn't find anything so I'm a bit curious if/how you automate that or if you manually do it on releasing.

add libcst as install_requires, print errors to stderr & return 1/0, add pre-commit hook & update config, 

---

CONTRIBUTING.md
flake8_trio/visitors/visitor91x.py
tests/autofix_files/trio100.py
tests/autofix_files/trio100.py.diff
tests/autofix_files/trio100_simple_autofix.py
tests/autofix_files/trio100_simple_autofix.py.diff
tests/autofix_files/trio910.py
tests/autofix_files/trio910.py.diff
tests/autofix_files/trio911.py
tests/autofix_files/trio911.py.diff
tests/autofix_files/trio91x_autofix.py
tests/autofix_files/trio91x_autofix.py.diff
tests/eval_files/trio100.py
tests/eval_files/trio100_noautofix.py
tests/eval_files/trio100_simple_autofix.py
tests/eval_files/trio910.py
tests/eval_files/trio911.py
tests/eval_files/trio91x_autofix.py
tests/eval_files/trio91x_noautofix.py
tests/test_flake8_trio.py

branched on top of #158 
F_ixes the sixth checkbox in #124 - "test that autofixed files don't generate errors", and also tests that autofixed files don't get further autofixes applied if run through the transformer again.
~~Finished, but somewhat messy - want to take a fresh look at `visitor91x.py` and the class structure there another day to see if I can make it less awful.~~
eval/autofix diffs are quite irritating when line numbers change, both in showing up in the diff and when developing when I manually edit the files - so it's possible I tweak something there in the future.
~~Feel free to review if you want, but I plan on cleaning it up and adding review comments so it should be easier after that.~~

test for autofix_files, fix some 91x autofixes, rejig eval_files

---

flake8_trio/__init__.py
flake8_trio/base.py
flake8_trio/runner.py
flake8_trio/visitors/flake8triovisitor.py
flake8_trio/visitors/helpers.py
flake8_trio/visitors/visitor100.py
flake8_trio/visitors/visitor91x.py
tests/autofix_files/trio910.py
tests/autofix_files/trio911.py
tests/autofix_files/trio91x_autofix.py
tests/autofix_files/trio91x_autofix.py.diff
tests/conftest.py
tests/eval_files/anyio_trio.py
tests/eval_files/no_library.py
tests/eval_files/trio103.py
tests/eval_files/trio103_no_104.py
tests/eval_files/trio103_trio.py
tests/eval_files/trio104.py
tests/eval_files/trio22x.py
tests/eval_files/trio23x.py
tests/eval_files/trio910.py
tests/eval_files/trio911.py
tests/eval_files/trio91x_autofix.py
tests/eval_files/trio91x_noautofix.py
tests/eval_files/trio_anyio.py
tests/test_changelog_and_version.py
tests/test_config_and_args.py
tests/test_flake8_trio.py

And just for funsies let's open a fourth PR :grin: 
It's branched on top of #162, so the diff will be *slightly* smaller once that's merged.
Ready for review, though I can probably polish it a bit if giving it another look tomorrow.
Had a decently long thonk on whether to just have an `--enable` and no `--disable`, or whether to get the full flake8 experience with `--extend-[...]` flags. Settled on this compromise.
91x does not respect `--autofix` parameter value properly atm, hence the commented out code with that, would like #159 in order to work on that.
Will probably have some merge conflicts and need rebasing once other PR's get merged

add standalone command line args

---

.github/workflows/ci.yml
tests/conftest.py
tox.ini

let's see how long they take to run in CI, I usually don't run them in my workflow locally since they're slow - but it's probably nice if they're run regularly *somewhere*

run fuzz in CI

---

flake8_trio/visitors/visitor_utility.py

New check, see https://github.com/MartinThoma/flake8-simplify/issues/171
This is the cause of all other PR's failing.

fix SIM910, dict.get with value==None (which is the default value)

---

README.md

F_ixes the second comment in #174
Lemme know if the examples doesn't work for you, but it should be this straightforward.

Add examples for running

---

flake8_trio/visitors/visitor100.py
tests/autofix_files/trio100.py
tests/autofix_files/trio100.py.diff
tests/eval_files/trio100.py
tests/test_flake8_trio.py

fix TRIO100 false alarm on nested context manager

---

flake8_trio/visitors/visitor91x.py
tests/autofix_files/trio910.py
tests/autofix_files/trio910.py.diff
tests/eval_files/trio910.py

Fix false 91x alarm on await in genexp target.

---

flake8_trio/base.py
flake8_trio/runner.py
flake8_trio/visitors/flake8triovisitor.py
flake8_trio/visitors/visitor_utility.py
tests/eval_files/noqa.py
tests/test_flake8_trio.py
tox.ini

fixes #181 
Implemented:
* respects `noqa`
* new pyright error about how to in-line silence stuff.
* it would be nice to catch errors-due-to-updated-linters with a bot, instead of me randomly encountering them when writing new PRs and being surprised.
* various small test improvements
* changes parametrized params to `test_eval` so summaries are more informative than e.g. `test_eval[False, True, TRIO100, path7]`
* sort errors on columns late, since columns have a habit of getting messed up and thrown around (and might be ignored anyway)
* ignore columns when checking with autofix
* the scenario here is two errors on the same line, the first which modifies the line, causing the second to have a different column
remaining TODO:
* don't autofix `noqa`'d errors
* ... ah shit, I have to kind …

respect noqa

---

flake8_trio/visitors/helpers.py
tests/autofix_files/trio100.py
tests/autofix_files/trio100.py.diff
tests/autofix_files/trio100_simple_autofix.py
tests/autofix_files/trio100_simple_autofix.py.diff
tests/eval_files/trio100_simple_autofix.py
tests/test_flake8_trio.py

added basic test case showing the problem, this was the cause of my confusion in #182 with comments disappearing.
todo: write a fix

fix trio100 removing trailing comment with same-line with

---

flake8_trio/__init__.py
flake8_trio/base.py
flake8_trio/runner.py
flake8_trio/visitors/flake8triovisitor.py
flake8_trio/visitors/visitor100.py
flake8_trio/visitors/visitor101.py
flake8_trio/visitors/visitor91x.py
pyproject.toml
tests/autofix_files/noqa.py
tests/autofix_files/noqa.py.diff
tests/autofix_files/noqa_testing.py
tests/autofix_files/noqa_testing.py.diff
tests/eval_files/noqa_no_autofix.py
tests/eval_files/noqa_testing.py
tests/eval_files/trio106.py
tests/eval_files/trio22x.py
tests/test_config_and_args.py
tests/test_flake8_trio.py

big refactor for noqa functionality fixing most of the remaining ones in #185, but as I added the test for all errors being properly noqa'd and was greeted with a wall of errors I realized it might be good to commit and push before tackling them. If it's a minor fix I'll just push/amend it to this PR, otherwise open a separate one.
* ~~Moves `# noqa` logic into `Flake8TrioVisitor_cst`, other than for ast visitors where some logic still is in `__init__.py`~~
* ~~utility visitor `NoqaHandler` removed~~
* add `--disable-noqa`, and use that instead of whether we're standalone to decide whether to parse noqa or not.
* ~~the list of `noqas` is no longer parsed once by a utility visitor, but instead parsed by each visitor. This is a performance hit (though probably not very large, if any) but is …

don't autofix noqa'd errors, add --disable-noqa, add non-passing test for noqa reliability

---

setup.py

while playing around I realized the `install_requires` weren't specified at all, so I quickly figured out minimum required versions for tests to pass and added them.

add version requirements on flake8&libcst

---

flake8_trio/visitors/helpers.py
flake8_trio/visitors/visitor103_104.py
flake8_trio/visitors/visitor91x.py
flake8_trio/visitors/visitor_utility.py
pyproject.toml
tests/test_config_and_args.py
tox.ini

enables the `noqa` checks in ruff, removing the noqa comments on rules not enforced by it, and disabling those rules in flake8.
unrelated:
randomly noticed that pretty-format-toml doesn't enforce consistent usage of `'` vs `"` for strings, so that's kind of a mess :unamused:

use ruff noqa handling

---

.github/workflows/ci.yml
.pre-commit-config.yaml
README.md
pyproject.toml
requirements-typing.txt

Some minor shuffling around of things now that we have pre-commit.ci
A bit ugly to duplicate the typing dependencies, but since we don't pin those it's nbd.
pyright is in pre-commit primarily because I run it locally, but the pre-commit bot will now also bump versions of it, causing it to actually run in the CI action, and everything magically works out.
todo:
* edit the branch protection rules. Will do that just before merging.

use pre-commit.ci, remove workflow step running pre-commit. Add pyright to CI workflow

---

tests/test_flake8_async.py

Seems like #217 [ran with py313a4](https://github.com/python-trio/flake8-async/actions/runs/8257803432/job/22588982343#step:3:12), but upon merging the [tests ran on py313a5](https://github.com/python-trio/flake8-async/actions/runs/8263081241/job/22603743419#step:3:12), which is how the warning snuck onto master.
Also required specifying the type better in the `visit_` functions for pyright to accept it.
Presumably we could entirely get rid of the `__dict__` assignment and only use `*args`, but not gonna bother.

fix py313a5 deprecationwarning

---

CHANGELOG.md
flake8_async/__init__.py
flake8_async/visitors/visitors.py
tests/eval_files/async110.py

async110 now also warns if looping .lowlevel.checkpoint()

---

CHANGELOG.md
flake8_async/__init__.py
flake8_async/visitors/visitor102.py
tests/eval_files/async102.py
tests/eval_files/async102_aclose.py
tests/eval_files/async102_aclose_args.py
tests/test_messages_documented.py

See #156 
I'm not sure if #156 also covers more general discussion on if/how to overhaul async102 and should remain open after this is merged.

ASYNC102 no longer raises warning for calls to `.aclose()` on objects

---

CHANGELOG.md
flake8_async/__init__.py
flake8_async/visitors/visitor91x.py
tests/autofix_files/async910.py
tests/autofix_files/async910.py.diff
tests/eval_files/async900.py
tests/eval_files/async910.py
tests/test_flake8_async.py

fixes #226 
Underlying issue was different try/except's sharing the same reference to self.try_state, due to not passing `copy=True` to `save_state()`.
I went through the other calls to `save_state` in the same visitor and added an explicit `copy=False` to the only other one that didn't already specify it. It's possible `save_state()` shouldn't have a default at all, or default to `True` since the performance loss from some extra copying would probably be negligible.

fix internal error in visitor91x

---

README.md
tests/test_config_and_args.py

Also adds tests to
1. catch if flake8 for some reason stops enforcing this
2. make sure that you can use `disable` in config files as a replacement.
fixes #230

add workaround for flake8_6 enforcing three-letter codes in config to readme

---

CHANGELOG.md
README.md
docs/rules.rst
flake8_async/__init__.py
flake8_async/visitors/visitors.py
tests/eval_files/async119.py

See #211 
@alicederyn
The issue is somewhat confusing at times to parse out what discussing pertains to async119 vs async102 vs hypotheticals, but I think this is what was settled upon.
I *think* this is a false positive with current implementation
```python
async def foo():
with open(""):
yield
```
i.e. the contextmanager is sync (and there are no awaits after the contextmanager?). Resolving that wouldn't be terribly complicated so I'll implement that if somebody confirms my understanding.
I didn't put much energy in formatting the entry in the readme, as that is on its way out. The links in the docs would probably be much cleaner with intersphinx or something, but leaving that for a different PR.

add async119: yield in contextmanager in async generator

---

CONTRIBUTING.md
flake8_async/visitors/visitor111.py
flake8_async/visitors/visitors.py
tests/eval_files/async111.py
tests/eval_files/async111_anyio.py
tests/eval_files/async111_asyncio.py
tests/eval_files/async112.py
tests/eval_files/async112_anyio.py
tests/eval_files/async112_asyncio.py

Fixes 2/3 tasks in #215
The logic in Visitor112 is incredibly messy and ugly, but works. Might rewrite it after sleeping on it.
I also realized that async112 has not been detecting
```python
async def foo():
async with trio.open_nursery() as nursery:
await nursery.start(bar)
```
and only worked properly on `start_soon`.

add asyncio/anyio taskgroup support to async111&112, update contributing.md

---

docs/conf.py
docs/rules.rst

I didn't bother a more comprehensive rewrite of blurbs, since a lot are getting rewritten in #248. Only changed a few to make sure that the intersphinx links worked.

add intersphinx, and modify a few blurbs to make use of it

---

.readthedocs.yaml
docs/conf.py
docs/requirements.txt

The documentation doesn't actually have any code examples that makes use of it (yet, #248) but I added it for the sake of reproducing https://github.com/felix-hilden/sphinx-codeautolink/issues/142 and thought I might as well commit it as a small PR.

add codeautolink

---

docs/changelog.rst
docs/index.rst
docs/rules.rst
docs/usage.rst
flake8_async/__init__.py
flake8_async/base.py
flake8_async/visitors/visitor2xx.py
tests/eval_files/async200.py
tests/test_config_and_args.py

Noticed this got missed in the big rename. Idk if there's any reason to use warnings.warn instead of printing on stderr.

deprecate --trio200-blocking-calls, replacing it with --async200-blocking-calls

---

docs/usage.rst
flake8_async/__init__.py
flake8_async/base.py
flake8_async/visitors/helpers.py
flake8_async/visitors/visitor91x.py
tests/autofix_files/async910.py
tests/autofix_files/exception_suppress_context_manager.py
tests/autofix_files/exception_suppress_context_manager.py.diff
tests/autofix_files/exception_suppress_context_manager_import_star.py
tests/autofix_files/exception_suppress_context_manager_import_star.py.diff
tests/eval_files/async910.py
tests/eval_files/async912.py
tests/eval_files/exception_suppress_context_manager.py
tests/eval_files/exception_suppress_context_manager_import_star.py
tests/test_flake8_async.py

Pretty straightforward. I wouldn't be totally shocked if this breaks something else in ASYNC91x, but I've spent a while trying to figure out edge cases and come up empty.
If you want support for `from contextlib import suppress` without having to specify `suppress` in the flag, it should be pretty doable to track the import like with other utility visitors.

add --exception-suppress-context-manager

---

docs/changelog.rst
docs/rules.rst
docs/usage.rst
flake8_async/__init__.py
flake8_async/visitors/visitor91x.py
pyproject.toml
tests/autofix_files/async910_insert_library.py
tests/autofix_files/async910_insert_library.py.diff
tests/autofix_files/async911_insert_library.py
tests/autofix_files/async911_insert_library.py.diff
tests/autofix_files/async913.py
tests/autofix_files/async913.py.diff
tests/autofix_files/exception_suppress_context_manager_import_star.py
tests/autofix_files/exception_suppress_context_manager_import_star.py.diff
tests/eval_files/async910_insert_library.py
tests/eval_files/async911_insert_library.py
tests/eval_files/async912.py
tests/eval_files/async913.py
tests/eval_files/async91x_noautofix.py
tests/eval_files/exception_suppress_context_manager_import_star.py

Adds a new check ASYNC913, indefinite-loop-no-guaranteed-checkpoint.
Will likely have some minor merge conflicts with #254 
Fixes #240.
Together with #254 it fixes the example given in #227. The error will be for the loop though, and not the context manager.
I also noticed a few bugs when implementing it, that also are fixed
* ASYNC911 crashed when trying to autofix
```python
while True: yield
```
because the autofix assumed the loop body was an `IndentedBlock`.
* ASYNC911 didn't add a library import when using InsertCheckPointsInLoopBody, i.e. when a checkpoint was needed due to the artificial statement injected at start of loop body. See eval_files/async911_insert_library.py
* ASYNC910 didn't add a library import when adding a checkpoint at the end of a function body. (as opposed to …

Add ASYNC913, indefinite-loop-no-guaranteed-checkpoint. Fix async91x bugs

---

docs/changelog.rst
docs/rules.rst
flake8_async/__init__.py
flake8_async/visitors/helpers.py
flake8_async/visitors/visitors.py
tests/eval_files/async120.py
tests/eval_files/async300.py
tests/test_flake8_async.py

Fixes #207, originally requested by @alicederyn in https://github.com/Zac-HD/flake8-async-archive/issues/5
The doc and error message can probably be improved.
I went for quite comprehensive checks for possible ways of not using the value. I don't think ~anybody that installs this plugin would hit any of them, but if/when this gets packaged into ruff I could imagine one of the weirder corner cases getting hit.

add ASYNC300 create-task-no-reference

---

docs/changelog.rst
flake8_async/__init__.py
flake8_async/visitors/visitor91x.py

make async913 disabled by default

---

docs/rules.rst
docs/usage.rst
flake8_async/visitors/visitor102.py
flake8_async/visitors/visitor_utility.py
flake8_async/visitors/visitors.py
tests/eval_files/async102.py
tests/eval_files/async112.py
tests/eval_files/async112_anyio.py
tests/eval_files/async112_asyncio.py
tests/eval_files/async113.py
tests/eval_files/async113_anyio.py
tests/eval_files/async113_asyncio.py
tests/test_flake8_async.py
tox.ini

Various small fixes I noticed while going through code/doc/issues.
* doc updates to 113 and `startable-in-context-manager`
* ASYNC102 await-in-finally-or-cancelled no longer treats `open_nursery` as a cancel scope.
* While you can make the cancelscope inside the nursery shielded with a timeout, that was never actually supported (there was no logic for seeing `nursery.cancelscope.shield = True`, only for `nursery.shield = True`, which is not possible)
* `open_nursery` is itself an async function so you can't safely open a nursery anyway.
*  async112 error message now specifies if it's a nursery or taskgroup.
* for dumb reasons I confused myself into thinking async111 & async112 didn't have asyncio support, and fully rewrote that from scratch :upside_down_face: But some of the stuff was …

various small fixes

---

docs/changelog.rst
docs/rules.rst
flake8_async/__init__.py
flake8_async/visitors/visitor102.py
tests/eval_files/async102.py
tests/eval_files/async102_aclose.py
tests/eval_files/async120.py

First part of #262 
It's maybe not great to have the same error messages for both 102 and 120, and docs could maybe be improved as well.

add async120, await-in-except

---

docs/changelog.rst
docs/rules.rst
flake8_async/__init__.py
flake8_async/base.py
flake8_async/visitors/visitors.py
setup.py
tests/eval_files/async900.py

Add config option for async900 decorators

---

docs/changelog.rst
docs/rules.rst
flake8_async/__init__.py
flake8_async/visitors/visitors.py
tests/eval_files/async121.py
tests/eval_files/async121_anyio.py
tests/eval_files/async121_asyncio.py
tests/test_flake8_async.py

closes #261 
Not sure whether to name the rule `control-flow-in-taskgroup`, `control-flow-in-nursery`, or `control-flow-in-taskgroup-or-nursery`. All previous nursery/taskgroup-related rules have in fact been about the cancelscope within them, such that none of them had to decide.
This made me want to double-check that this rule *is* exclusive to nursery/taskgroups, and that the rule shouldn't be expanded to also trigger on control flows inside cancelscopes, but I cannot personally come up with anything at least.
The test isn't *fully* exhaustive with nested loops and stuff, but the visitor is simple enough I think it's unlikely something would sneak through.

add async121 control-flow-in-taskgroup

---

.pre-commit-config.yaml
docs/changelog.rst
docs/rules.rst
docs/usage.rst

Fixes https://github.com/python-trio/flake8-async/pull/282#discussion_r1745922270
Adds https://pypi.org/project/sphinx-lint/ and fixes all errors pointed out by it.
Also fixing a broken bullet list I manually noticed
I did not add any of the following linters, but that could be revisited
* https://github.com/rstcheck/rstcheck which pointed out the markdown url in `changelog.rst`, but it was otherwise very noisy and didn't point out any actual errors.
* https://github.com/PyCQA/doc8 complains about a ton of lines being too long, so if we want to stick with a max char line length it's the tool to go for. I personally feel it's got much less of an upside compared to code, and can be a major hassle to reflow lines after editing them instead of just letting autowrap handle it.
* …

Rst linting

---

docs/changelog.rst
flake8_async/__init__.py
flake8_async/visitors/visitors.py
tests/eval_files/async113.py
tests/eval_files/async121.py

Fixes #286 
I also did a search for `visit_FunctionDef` and `visit_AsyncFunctionDef` in the codebase and caught the same error for async113 (though it should very rarely occur for 113). At first glance a couple other visitors had the same problem, until I noticed those were cst visitors (which instead has an `asynchronous` attribute).
For 113 we could consider having the logic for `visit_FunctionDef` being the same as `visit_AsyncFunctionDef` instead of always setting `self.aenter = False` in case users are transforming sync methods to async methods, but given such exotic stuff we're maybe better off staying away and avoiding super obscure false positives.
We could consider adding a test that checks if any AST visitors only has one of the visitors defined, and could do the same for …

ASYNC113 & ASYNC121 false alarm with nested sync functions

---

docs/changelog.rst
flake8_async/__init__.py
flake8_async/visitors/visitor102.py
tests/eval_files/async102.py
tests/eval_files/async102_anyio.py
tests/eval_files/async102_asyncio.py
tests/eval_files/async102_trio.py

Fixes most of #283 and some other things I noticed, only remaining thing being checking other rules for if they should also have special handling of `open_nursery`/`create_task_group`.
Note that `trio.move_on_after(shield=True)` has not been released yet

fix various issues with ASYNC102

---

docs/changelog.rst
docs/rules.rst
flake8_async/__init__.py
flake8_async/visitors/visitors.py
tests/eval_files/async122.py
tests/test_flake8_async.py

fixes #290 
It doesn't handle the complex case of
```python
foo = trio.fail_after
bar = foo(5)
trio.sleep(3)
with bar:
...
```
and while it would be possible to error anytime somebody refers to `trio.fail_after` not directly inside a `with` call it'd probably mostly just lead to unnecessary false positives.

add ASYNC122 delayed-entry-of-relative-cancelscope

---

docs/changelog.rst
flake8_async/__init__.py
flake8_async/visitors/visitor91x.py
tests/autofix_files/async100.py
tests/eval_files/async100.py

fixes #295 
I noticed this comment... :facepalm: 
https://github.com/python-trio/flake8-async/blob/db5317c9d9c18919390f43c56d692dd702651032/flake8_async/visitors/visitor91x.py#L43-L46

fix assertionerror with infinite loop in context manager

---

.pre-commit-config.yaml
docs/changelog.rst
docs/rules.rst
flake8_async/__init__.py
flake8_async/visitors/__init__.py
flake8_async/visitors/visitor123.py
tests/eval_files/async123.py
tests/eval_files/async123_py311.py
tests/test_flake8_async.py

messy and imperfect, but should catch most usage and hopefully Ruff can implement this properly :crossed_fingers: 
TODO:
* changelog, bump version
* write documentation
* figure out a name. `reraise_child_exception` is clean but "child exception" is not established nomenclature. `reraise_exception_group_sub_exception`? `bad_exception_group_flattening`?

initial implementation of ASYNC123

---

docs/changelog.rst
docs/rules.rst
flake8_async/__init__.py
flake8_async/visitors/__init__.py
flake8_async/visitors/visitor102_120.py
pyproject.toml
tests/eval_files/async102.py

I didn't realize just how trivial it was to enable this functionality lol
also some random small changes
Fixes another part of #262, only the new rule for `@asynccontextmanager` left.

102 now also checks __aexit__

---

.github/workflows/ci.yml
docs/changelog.rst
docs/rules.rst
docs/usage.rst
flake8_async/__init__.py
flake8_async/visitors/visitor101.py
flake8_async/visitors/visitors.py
tests/eval_files/async101.py
tests/eval_files/async119.py
tests/eval_files/async900.py

fixes #315 
I noticed the flag wasn't documented at all in `usage.rst`, so added it there.
I also think it should be enabled for ASYNC119?
The flag becomes somewhat weirdly named for ASYNC101 since it will also suppress errors in sync functions. Idk if it warrants a rename, or I should just mention it in the docs, or explicitly only make it have an effect on async funcs, or something else.

async101 & async119 now respects transform-async-generator-decorators

---

docs/changelog.rst
docs/glossary.rst
docs/rules.rst
flake8_async/__init__.py
flake8_async/visitors/visitor91x.py
tests/autofix_files/async100.py
tests/autofix_files/async100.py.diff
tests/autofix_files/async100_trio.py
tests/autofix_files/async100_trio.py.diff
tests/eval_files/async100.py
tests/eval_files/async100_trio.py

I was cleaning up old branches in my fork, and it... seems like I never opened a PR for this? Wrote it several months ago, so decided to just rebase and clean it up

async100 now ignores trio.open_nursery and anyio.create_task_group

---

docs/changelog.rst
flake8_async/__init__.py
flake8_async/visitors/helpers.py
flake8_async/visitors/visitor91x.py
flake8_async/visitors/visitors.py
tests/autofix_files/async100.py
tests/eval_files/async100.py

fix crash. Make identifier_to_string less footgunny.

---

docs/changelog.rst
docs/glossary.rst
docs/rules.rst
flake8_async/__init__.py
flake8_async/visitors/flake8asyncvisitor.py
flake8_async/visitors/visitor91x.py
tests/autofix_files/async100.py
tests/autofix_files/async100_anyio.py
tests/autofix_files/async100_anyio.py.diff
tests/autofix_files/async100_trio.py
tests/autofix_files/async100_trio.py.diff
tests/eval_files/async100.py
tests/eval_files/async100_anyio.py
tests/eval_files/async100_trio.py

unreverts #317 (partially reverted in #326) and fixes #325

ASYNC100 now treats start_soon() as a cancel point

---

.github/workflows/ci.yml
.pre-commit-config.yaml
docs/changelog.rst
docs/usage.rst
tests/check_changelog_and_version.py

move changelog&version check to pre-commit and to a separate CI job that skips on skip-release label
Remaining quirks:
1. The job won't re-run automatically on label assignment. Claude is telling me I can get there by splitting up the workflows across files, I'll give that a try later.
2. A CHANGELOG run will fail after getting merged to main, because it loses the label. Not sure how to resolve that neatly; maybe just always pass `--allow-future` if it triggers on `push`.
The test file is kind of ugly now in that it both looks like a pytest file and doesn't. I should probably add some comments at the very least.
EDIT: actually, I shouldn't skip the CI job with the skip-release label - I should just make that pass `--allow-future` as well.
(also the flag is somewhat opaquely named, probs …

improve changelog/release handling

---

.github/workflows/ci.yml
.pre-commit-config.yaml
pyproject.toml

no reason not to keep these synced with latest released python

bump various tools to use 3.13

---

docs/changelog.rst
docs/rules.rst
docs/usage.rst
flake8_async/__init__.py
flake8_async/visitors/visitor91x.py
tests/autofix_files/async913_trio_anyio.py
tests/autofix_files/async913_trio_anyio.py.diff
tests/eval_files/async912.py
tests/eval_files/async913_trio_anyio.py
tests/test_flake8_async.py
tox.ini

fixes #340 and extends it to ASYNC912 as well
I felt kinda silly realizing the `trio.open_nursery` <-> `anyio.create_task_group` replacement only now, that could clean up eval_files for... 100, 101, 105, 111, 112, 113 & 121 :sweat_smile:

make ASYNC912 and 913 care about cancel points, and ignore schedule points

---

flake8_async/__init__.py
flake8_async/visitors/helpers.py
flake8_async/visitors/visitor123.py
flake8_async/visitors/visitor91x.py
pyproject.toml
tests/test_config_and_args.py
tox.ini

fixes #332 - though in hindsight we barely have any version-specific code so this PR mostly just fiddles around with various config stuff
found a couple pragma no-cover/branch that weren't needed, and realized `--per-file-disable` added in #348 never got any tests at all, so will have to do a followup PR on that
big warning for anybody considering coverage-conditional-plugin: the example in their readme is completely backwards https://github.com/wemake-services/coverage-conditional-plugin/pull/227

add coverage-conditional, rejig some config stuff

---

.pre-commit-config.yaml
docs/changelog.rst
docs/usage.rst
flake8_async/__init__.py
flake8_async/visitors/visitor102_120.py
flake8_async/visitors/visitor103_104.py
flake8_async/visitors/visitor91x.py
tests/autofix_files/async91x_py311.py
tests/autofix_files/async91x_py311.py.diff
tests/eval_files/async102_120_py311.py
tests/eval_files/async103_104_py311.py
tests/eval_files/async912_py311.py
tests/eval_files/async91x_py311.py
tests/test_flake8_async.py

fixes one half of #173 (the other being match/case)
First time trying out Claude Code, I more or less had to rewrite everything it generated in the end - but they gave it a good shot!

add except* support to 102, 103, 104, 120, 910, 911 & 912

---

.pre-commit-config.yaml
docs/changelog.rst
docs/usage.rst
flake8_async/__init__.py
flake8_async/visitors/visitor103_104.py
flake8_async/visitors/visitor91x.py
flake8_async/visitors/visitor_utility.py
tests/autofix_files/async91x_py310.py
tests/autofix_files/async91x_py310.py.diff
tests/eval_files/async103_104_py310.py
tests/eval_files/async91x_py310.py

Support structural pattern matching in ASYNC103,104 and 91X

---

docs/changelog.rst
docs/rules.rst
docs/usage.rst
flake8_async/__init__.py
flake8_async/visitors/helpers.py
flake8_async/visitors/visitor102_120.py
flake8_async/visitors/visitors.py
tests/eval_files/async125.py
tests/test_flake8_async.py

fixes #353 
anyio does not currently have `CancelScope(relative_deadline=...)`, but @agronholm seemed open to adding it so I'm not gonna bother messing around with the error message for now.

add ASYNC125 constant-absolute-deadline

---

docs/changelog.rst
docs/rules.rst
docs/usage.rst
flake8_async/__init__.py
flake8_async/visitors/visitors.py
tests/eval_files/async900.py

fixes #370 
I thought this was gonna be a one-line fix, but ended up getting really messy. There's definitely a cleaner way of implementing this, but it should work... :upside_down_face: 
The reason it gets messy is because `has_decorator`->`_get_identifier` only matches against the last part of an attribute, but I want `trio.as_safe_decorator` in the error message, so the message and the implementation gets a mismatch. The main alternative approach would be to have separate lists of decorators for the error message and the logic.

add trio.as_safe_channel to async900 safe decorators

---

docs/changelog.rst
docs/usage.rst
flake8_async/__init__.py
flake8_async/visitors/visitors.py
tests/eval_files/async113.py
tests/eval_files/async113_trio.py

fixes #263 
I came up with another false alarm that requires a bigger fix, so leaving that one as a tomorrow problem. It appears that 2.5 years is past my limit of fully remembering complicated details of the innards of this code base :sweat_smile:

fix async113 false alarms

---

docs/changelog.rst
docs/usage.rst
flake8_async/__init__.py
flake8_async/visitors/visitor102_120.py
tests/eval_files/async102.py
tests/eval_files/async120.py

async102 & async120 no longer requires cancelscope to have a timeout
